config/routes.rb
Rails.application.routes.draw do

get '/search/:id', to: 'lists#search'

  resources :tags
  get '/welcome', to: 'application#welcome', as: "welcome_page"
  root to: 'application#welcome'
  devise_scope :user do
    get 'login', to: 'devise/sessions#new', as: 'login'
    get 'signup', to: 'devise/registrations#new', as: 'signup'
  end

  resources :cards

  resources :lists do
    resources :cards, only: [:new, :edit, :update, :destroy]
    resources :tags, only: [:new, :edit, :update, :destroy, :create]
  end 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users, :controllers => {:registrations => 'registrations', :omniauth_callbacks => 'callbacks'}

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
    belongs_to :list

    def self.delete_list_cards(cards)
        cards.each {|card| card.destroy}
    end 
end

app/models/list.rb
class List < ApplicationRecord
    belongs_to :user 
    has_many :cards 
    has_many :lists_tags
    has_many :tags, through: :lists_tags

end

app/models/lists_tag.rb
class ListsTag < ApplicationRecord 
    belongs_to :list
    belongs_to :tag
end 

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :lists_tags 
    has_many :lists, through: :lists_tags

    scope :search_tags, ->(tag) { where("title == ?", tag)}
end

app/models/user.rb
class User < ApplicationRecord
  has_many :lists 
  has_many :cards, through: :lists 
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable

  def self.from_omniauth(auth)
     where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider 
      user.username = auth.info.name 
      user.uid = auth.uid 
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end 
  end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    def welcome 
        @current_user = current_user
    end 
end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController 
    def github
        @user = User.from_omniauth(request.env["omniauth.auth"])
        sign_in_and_redirect @user 
    end 
end 

app/controllers/cards_controller.rb
class CardsController < ApplicationController

    def show 
        @card = current_user.cards.find(params[:id])
    end 

    def new 
        if params[:list_id] && !List.exists?(params[:list_id])
            redirect_to lists_path, alert: "List not found."
        else 
            @card = Card.new(list_id: params[:list_id])
        end 
    end 

    def create 
        @card = Card.new(card_params)

        if @card.save
            redirect_to @card.list 
        else
            render :new
        end
    end 

    def edit 
        if params[:list_id]
            list = current_user.lists.find_by(id: params[:list_id])
            if list.nil?
                redirect_to lists_path, alert: "List not Found."
            else
                @card = list.cards.find_by(id: params[:id])
                redirect_to list_cards_path(list), alert: "Post not found." if @card.nil?
            end
        else 
            @card = Card.find(params[:id]) 
        end 
    end 

    def update
        @card = Card.find(params[:id])

        @card.update(card_params)

        if @card.save
            redirect_to @card 
        else
            render :edit 
        end
    end 

    def destroy 
        @card = current_user.cards.find_by(id: params[:id])
        @card.destroy
        flash[:notice] = "Item Deleted"
        redirect_to @card.list  
    end 


    private 

    def card_params 
        params.require(:card).permit(:body, :list_id)
    end 
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

    def index 
        @lists = current_user.lists
    end 

    def show 
        @list = current_user.lists.find(params[:id])
        @cards = @list.cards 
    end 

    def new 
        @list = current_user.lists.build
    end 

    def create 
        @list = current_user.lists.create(list_params)

        if @list.save
            redirect_to @list
        else 
            render :new
        end 
    end 

    def edit 
        @list = current_user.lists.find(params[:id])
    end 

    def update 
        @list = current_user.lists.find(params[:id])
        @list.update(list_params)
        if @list.save 
            redirect_to @list 
        else 
            render :edit 
        end 
    end 

    def destroy 
        @list = current_user.lists.find(params[:id])
        Card.delete_list_cards(@list.cards)
        @list.destroy 
        flash[:notice] = "List deleted."
        redirect_to lists_path
    end 

    def search 
        @tag = Tag.find(params[:id])
        @tag_lists = Tag.search_tags(@tag.title)
        binding.pry
    end 

    private 

    def list_params
        params.require(:list).permit(:title)
    end 
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController 
    private 

    def signup_params 
        params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end 

    def account_update_params
        params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end 
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

    def new 
        if params[:list_id] && !List.exists?(params[:list_id])
            redirect_to lists_path, alert: "List not found."
        else 
            @list = current_user.lists.find_by(id: params[:list_id])
            @tag = @list.tags.build
        end    
    end  

    def create
        @list = current_user.lists.find_by(id: params["list_id"].to_i)
        @tag = @list.tags.create(tag_params)
        if @tag.save
            redirect_to @list
        else 
            render :new 
        end
    end 

    def edit 
        @tag = Tag.find(params[:id])
    end 

    def update 
        @tag = Tag.find(params[:id])

        @tag.update(tag_params)

        if @tag.save
            redirect_to list_path
        else 
            render :edit
        end 
    end 

    def destroy 
        @tag = Tag.find(params[:id])
        @tag.destroy
        flash[:notice] = "Tag Deleted"
        redirect_to list_path

    end 

    private 

    def tag_params 
        params.require(:tag).permit(:title)
    end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/application/welcome.html.erb
<% if @current_user == nil%>
    <h1>Sign up or login</h1>
    <p>Start creating lists </p>
<% else %>
    <h1>Welcome</h1>
    <p><%= link_to "My Lists", lists_path %> <br>
    <%= link_to "Create New Lists", new_list_path %> <br>
<% end %>

app/views/cards/_form.html.erb
<%= form_for(@card) do |f| %>
    <label>Item body:</label><br>

    <%= f.hidden_field :list_id %>

    <%= f.text_field :body %><br>
    <%= f.submit  %>
<% end %>

app/views/cards/edit.html.erb
<h1>Edit List Item</h1>
<p><%= link_to "Cancel", list_path(@card.list) %> </p>
<%= render 'form' %>

app/views/cards/new.html.erb
<h1>New List Item</h1>
<p>For: <%= link_to @card.list.title, list_path(@card.list) %> </p>
<%= render 'form' %>

<p><%= link_to "Cancel", list_path(@card.list) %> </p>

app/views/cards/show.html.erb
<h1>List: <%= link_to @card.list.title, list_path(@card.list) %> </h1>
<p><%= @card.body %></p><br>
<p> <%= link_to "Edit Item", edit_list_card_path(@card.list, @card) %></p><br>
<%= link_to "Delete Item", @card, class: "delete_link", method: :delete %>
<p><%# link_to "Delete Item,"  delete_path%> </p>

app/views/layouts/_nav.html.erb
<nav>
    <ul>
        <li><%= link_to "Home", root_path %></li>
        <% if !user_signed_in?%>
            <li><%= link_to "Signup", signup_path %></li>
            <li><%= link_to "Login", login_path %></li>
        <% else %>
            <li><%= link_to "Logout", destroy_user_session_path, method: "delete" %></li>
            <p><%= current_user.username %> </p>
        <% end %>
    </ul>

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ListlyRailslistgenerator</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.css"
      integrity="sha256-a2tobsqlbgLsWs7ZVUGgP5IvWZsx8bTNQpzsqCSm5mk="
      crossorigin="anonymous"
    />

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <div class="container">
      <h1 class="brand"><span>Listly</span></h1>
      <div class="wrapper">
        <div class="company-info">
          <%= render 'layouts/nav' %>

        </div>
        <div class="contact">
            <%= yield %>
        </div>
      </div>
    </div>

    <script src="https://www.gstatic.com/firebasejs/7.5.0/firebase-app.js"></script>
    <script src="main.js"></script>
  </body>
</html>

app/views/lists/_from.html.erb
<%= form_for @list do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= f.submit %>
<% end %>

app/views/lists/edit.html.erb
<h1>Editing <%= @list.title %></h1>

<%= render "from" %>
<p><%= link_to "Cancel", lists_path %> </p>

app/views/lists/index.html.erb
<h1>My Lists</h1>

<% @lists.each do |list| %>
    <div>
        <p><%= link_to list.title, list_path(list) %>(<%= link_to "Edit", edit_list_path(list) %>)(<%= link_to "Delete", list, class: "delete_link", method: :delete %>)</p>
    </div>
<% end %>

<h3><%= link_to "Add List", new_list_path %> </h3>

app/views/lists/new.html.erb
<h1>Create a List</h1>
<p><%= link_to "Cancel", lists_path %> </p>
<%= render "from" %>

app/views/lists/search.html.erb
<h1>Lists with Tag: <%= @tag.title %></h1>

<% @tag_lists.each do |tag| %>
    <% tag.lists.each do |list| %>
        <div>
            <p><%= link_to list.title, list_path(list) %>(<%= link_to "Edit", edit_list_path(list) %>)(<%= link_to "Delete", list, class: "delete_link", method: :delete %>)</p>
        </div>
    <% end %>
<% end %>

<h3><%= link_to "Add List", new_list_path %> </h3>

app/views/lists/show.html.erb
<h1><%= @list.title %></h1>

<% if @list.tags.empty? %>
    <%= link_to "Add Tag", new_list_tag_path(@list) %>
<% else %>
        <% @list.tags.each do |tag| %>
        <p>Tag:<%= tag.title%>(<%= link_to "Edit", edit_list_tag_path(tag) %>)(<%= link_to "Delete", tag, method: :delete %>)(<%= link_to "Related Lists", "/search/#{tag.id}" %>)</p>
    <% end %>
<% end %>

<p><%= link_to "My Lists", lists_path %> </p>
<% if @cards.empty? %>
    <p>List empty:</p>
<% else %>
    <% @cards.each do |card| %>
        <%= link_to card.body, card_path(card) %>(<%= link_to "Edit", edit_card_path(card) %>)(<%= link_to "Delete", card, method: :delete %>)<br>
    <% end %>
<% end %>

<h3><%= link_to "Add Item", new_list_card_path(@list) %></h3>

app/views/tags/edit.html.erb
<%= form_for(@tag) do |f| %>
    <label>Tag name:</label><br>

    <%= f.text_field :title %><br>
    <%= f.submit  %>
<% end %>

app/views/tags/new.html.erb
<h1>New Tag</h1>
<p>For: <%= link_to @list.title, list_path(@list) %> </p>
<%= form_for(@tag) do |f| %>
    <label>Tag name:</label><br>

    <%= hidden_field_tag "list_id", @list.id %>

    <%= f.text_field :title %><br>
    <%= f.submit  %>
<% end %>
<p><%= link_to "Cancel", list_path(@list) %> </p>